### ISSUE TITLE
2: Calendar

### ISSUE THREAD

**Issue by mamallama** [Communicant/app#1]
Basically, we need to:
- [ ] emulate Google calendar API
-  [ ]  fixed the requests in order to:
- [ ] post
- [ ] get
- [ ] patch

Don't forget to fix:
- [ ] child_name
- [ ] change time format to a more friendly one
- [ ] status can not be null 
- [ ] Use the list of endpoints on the Google API calendar to test our mock API's endpoints/functionality
- [ ] Recreate a JSON file that mimics a Google Calendar API

User Stories: 
- Mediator should be able to create a calendar
- Logged in Parent should be able to view shared calendar
- Logged in Parent should be able to create event
- By default, Event should show up as "Pending" 
- Event status changes from "Pending" to "Approved" when other Parent has accepted the event
- Events cannot be deleted
- The default status for Updated Events is "Pending" 
- "Pending" status for Updated Events will only change when other Parent has accepted the event

**Comment by boshnivolo** [comment]
**Actually ranked a 4, but there is no option on the dropdown menu for a 4. Weird.**
