### ISSUE TITLE
2.Expenses page. 

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#11]
#### Header: same for all the rest of the pages except for login.
- [x] name of the app
- [x] button for expenses
- [x] button for inbox
- [x] button for calendar
- [x] button for profile
- [x] button for log out

Two main tables:  Costs and paid.
#### Costs table:
- [x] title Costs
##### For each expense:
- [x] title of the expense
- [x] due date
- [x] amount

Paid shows only what logged in user has paid.

When paid, move to paid table.

Create a new costs and new paid `input`.

Total on the bottom in both paid and costs.

Transfer to PDF

Link to paypal at the bottom of the page.

```
User stories for this page:

   enter expenses related to their kids care.
   transfer money to the other parent. (stripe/paypal)
```

**Comment by boshnivolo** [comment]
**PRs for the Expenses page**: 
- https://github.com/Communicant/app/pull/28
- https://github.com/Communicant/app/pull/34
- https://github.com/Communicant/app/pull/40
- https://github.com/Communicant/app/pull/41
- https://github.com/Communicant/app/pull/44
- https://github.com/Communicant/app/pull/46
- https://github.com/Communicant/app/pull/48
