### ISSUE TITLE
User Story #1.Parents and mediator can view the costs

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#13]
1.Parents can view the costs that they have to pay for their children care. 
They see different costs in a list and in each one they can see:
- [x] due date of the cost.
- [x] the title of the cost.
- [x] amount of the cost.

For FE, we need:
- [x] a block to list of the costs
- [x] a list of costs inside and for each with:
  - [x] date 
  - [x] title 
  - [x] amount 

For Ruby, we need:
- [x] table for cost, including:
  - [x] title
  - [x] amount
  - [x] parent id
  - [x] due date
  - [x] paid (with a boolean value of true or false) maybe better paid_by (date) ????????????????????
- [x] methods for separating items, based on whether or not they have been paid.

**Comment by al-the-x** [comment]
Better for reporting: "paid at" date.

**Comment by rosalsm** [comment]
For Ruby table, better "paid at" instead of paid (true/false)

**Comment by mamallama** [comment]
paid_at is fine.

**Comment by boshnivolo** [comment]
**PRs for the Costs Feature**: 
- https://github.com/Communicant/app/pull/28
- https://github.com/Communicant/app/pull/34
- https://github.com/Communicant/app/pull/40
- https://github.com/Communicant/app/pull/44
- https://github.com/Communicant/app/pull/48
