### ISSUE TITLE
As a registered user I can see payments related to my account

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#14]
Parents can see payments that they have done. Every time each parent make a payment, we need to create a new payment in the block. Parent 1 can see all the payments from both parents.  
Parents will see:
- [x] how much they paid
- [x] title of the payment
- [x] date they paid
- [x] who made the payment
- [x] payments will be ordered by cost ?????????????????? can we do this filter?
- [x] payments will be ordered by date in each cost???????????and this filter?

For FEE
- [x] a list containing the date, title, amount, and parent who paid, for each payment

For Rails:
- [x] a Payment table that contains
  - [x] amount, parent_id, cost_id, date
  - [x] a method that adds all payments with the same cost_id
  - [x] a method that will update a costs paid field to true once the total amount of payments matches the amount of the cost.

**Comment by al-the-x** [comment]
Can the list of payments be filtered? So I can see only _my_ payments vs only _theirs_...? What about "on time" vs "overdue"...?

**Comment by rosalsm** [comment]
Ruby (Anthony says so) I will ask Renee too about the filter options. 
Parents can see all payments (theirs and others)
No consideration for overdue at this point.

**Comment by boshnivolo** [comment]
**PRs from Payments Feature**:
- https://github.com/Communicant/app/pull/41
- https://github.com/Communicant/app/pull/44
- https://github.com/Communicant/app/pull/46
- https://github.com/Communicant/app/pull/48
