### ISSUE TITLE
User Story #2. Parents can add a new cost.

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#15]
Parents can add a new costs, they should be able to add this information in the new cost.
- [x] due date of the cost.
- [x] the title of the cost.
- [x] amount of the cost.

For FE or Ruby:
- [x] form with inputs for:
  - [x] date 
  - [x] title 
  - [x] amount 
- [x] Submit button.

**Comment by al-the-x** [comment]
More details here: what does the form for asking an Expense look like? What is required, what is optional? Where does the form submit? What happens next? Does anyone need to confirm the Expense?

**Comment by rosalsm** [comment]
We have a draw for the costs. It is a column in the expenses page where parents can see what has to be paid.
All fields are required (basic minimum info)
Submit button add this new cost to the list of costs in the costs column.
No confirmation required based on user stories.

**Comment by mamallama** [comment]
Back end done.

**Comment by boshnivolo** [comment]
**PR regarding the "Adding of new Costs"**: https://github.com/Communicant/app/pull/34/files

**Commits for the Costs Branch**: https://github.com/Communicant/app/commits/feature/costs
