### ISSUE TITLE
User Story #4. Parents can add a new payment

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#16]
Parents can create a new payment to add. Parent will need:
- [x] date of the payment
- [x] title of the cost
- [x] amount

For each cost that is paid, we can add a total amount paid???????????????????

For FE, we need:
- [x] form with:
  - [x] date
  - [x] title of the cost????????? or getting list of costs to select
  - [x] amount

**Comment by mamallama** [comment]
Back-end: 

creating a form with fields that FE/Rails discussed at length AND what needs to be displayed.

**Comment by mamallama** [comment]
Back end done

**Comment by boshnivolo** [comment]
**PR regarding the "Adding of New Payments"**: https://github.com/Communicant/app/pull/41/files

**Commits for the Payments Branch**: https://github.com/Communicant/app/commits/feature/payments
