### ISSUE TITLE
As a mediator I can register for an account

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#19]
Mediators can register so they can see their account.

In order to register they need:
- [ ] first name
- [ ] last name
- [ ] email address
- [ ] password
- [ ] confirm the password
- [ ] social worker/ friend/ relative ???????????????? or maybe we don't need this.

For FE:
- [ ] form
- [ ] with username, email, password, confirm password.
- [ ] submit button

**Comment by mamallama** [comment]
All registration and profile related issues were set to iteration 4, this one and a few others were left as "Iteration 3" because parts of it were done. I'm moving it to 4.
