### ISSUE TITLE
As a mediator I can log in

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#20]
Mediators can login so they can see their account.
In order to login we need:
- [x] email address
- [x] password

For FE:
- [x] form with email and password
- [x] submit button

for Rails:
- [x] Authentication for email and password
- [x] Session for logged-in user

**Comment by mamallama** [comment]
https://github.com/Communicant/app/pull/79

**Comment by al-the-x** [comment]
Confused about whether or not this is / was complete... Please explain _in the comments_ when you close / reopen something...

**Comment by ajellis** [comment]
The session is set up correctly, but the login button on the homepage doesn't actually log you in. So we closed it when we thought it worked, and reopened once we realized it didn't.
