### ISSUE TITLE
As a mediator I can see the mediator dashboard that houses all related cases

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#21]
Once the mediator has logged in, they can see their account. It will be a Dashboard where they can see all cases.
- [ ] cases #
- [ ] parents name (and child name????)

For FE:
- [ ]  sections for each case with an `<a>` in the case# and name of the parents

For Rails:
- [x] database table for cases
  - [x] case_number
  - [x] mediator_id

**Comment by mamallama** [comment]
Cases table created. About to commit to develop
