### ISSUE TITLE
User Story#11. Parents and mediator can go to the app page

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#23]
When they go to the app page they can see:
- [x] place to login
- [x] place to register
- [x] header with the app name
- [x] body of the page with app explanation.

For FE:
- [x] header
- [x] nav with `<a>` for login and register
- [x] body page with what the app is doing for them `<p>`

**Comment by mamallama** [comment]
This is all home page. Done

**Comment by rosalsm** [comment]
Jasmine was working on this feature on the old FE repo and Rosa updated for this repo

**Comment by rosalsm** [comment]
PR
https://github.com/Communicant/app/pull/54
https://github.com/Communicant/app/pull/56
