### ISSUE TITLE
As a mediator I can view my related profile page

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#24]
Different types of users can view their profiles upon log in. 
View for the profile is already done. It is going to be the same view that the users page can go to details or update the users. After this iteration, backend will link the specific user to their specific profile and just theirs. That way no one can  view other profile but theirs.

Mediators could see parents profile too in order to check info like address or email or phone number ??????????? to Renee

In the form for profile, FE has to style and organize these different parts:
- [x] first name
- [x] last name
- [x] address
- [x] email
- [x] phone number
  - [ ] work
  - [ ] home
  - [ ] cell
- [x] case number
  ?????? case id
  ?????? password
- [x] case

**Comment by mamallama** [comment]
Back-end: 
- [x] Create Users table
- [ ] Define associations
- [ ] Create sessions
- [ ]  bcrypt
- [ ] take care of authorization/authentication through models/controllers.

**Comment by mamallama** [comment]
This is definitely a FE/Rails issue. 
Rosa and I are tackling it.

**Comment by rosalsm** [comment]
PR
https://github.com/Communicant/app/pull/49
https://github.com/Communicant/app/pull/47
https://github.com/Communicant/app/pull/95
