### ISSUE TITLE
As a registered user I can view the information page 

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#26]
Parents and mediators can see information shared like school info, after school activities, doctor's office, babysitter,etc. This info will be display in:
- [ ] name or company
- [ ] telephone number
- [ ] address
- [ ] email address
- [ ] person in charge or contact person or doctors name or whatever is necessary depending on the case

For FE:
We need to add a form with the following inputs:
- [ ] name or company
- [ ] telephone number
- [ ] address
- [ ] email address
- [ ] person in charge or contact person or doctors name or whatever is necessary depending on the case

**Comment by al-the-x** [comment]
What's "the information page"...? Landing page? Shared contacts?

**Comment by rosalsm** [comment]
The info page is where they can share information about school address, doctor's office, after school activities,etc. Both parents need to know this details.

**Comment by al-the-x** [comment]
More details needed for this feature, then: what kind of information, how is it displayed, in what order, etc.

**Comment by rosalsm** [comment]
We haven't even started with this issue yet. Just the title to know what has to be done

**Comment by mamallama** [comment]
This is an optional shared information page. 
School, After school programs, babysitters, doctors, addresses, phone number, person in charge, etc.

**Comment by al-the-x** [comment]
Without a milestone assignment (or any other label), I can't tell which stories are in active development for the current iteration vs planned for a future iteration.

**Comment by rosalsm** [comment]
we have milestones and labels for all issues/user stories right now

**Comment by al-the-x** [comment]
I see. They're just out of order... Milestones without a date assigned float to the top of the list.
