### ISSUE TITLE
R. Profile: Parents can update their own profile

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#29]
User Story #16. Parents can update their own profile.

Different types of users can view their profiles upon log in. 
View for the profile is already done. It is going to be the same view that the users page can go to details(show) or update the users. During this iteration, backend will link the specific user to their specific profile and just theirs. That way no one can view other profiles but theirs.
- [ ] Mediators can see parents profile too

Profile form includes:
- [x] first name
- [x] last name
- [x] address
- [x] email
- [x] phone number
  - [ ] work
  - [ ] home
  - [ ] cell
- [x] case number
- [x] case id

**Comment by mamallama** [comment]
Form with: 
- [ ] Name
- [ ] Email
- [ ] Phone Number
- [ ] Address
- [ ] Child 1 Name
- [ ] Way to add More Children
- [ ] Case Number
- [ ] Mediator Name
