### ISSUE TITLE
As a registered parent user I can see the profile page related to me

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#30]
For now we have users but the details page of a user, it will profile page for individual users. 

Parents can see their profile with:
- [x] name
- [x] last name
- [x] email address
- [x] address
- [x] telephone number
  - [ ] home
  - [ ] cell
  - [ ] work
- [ ] child name
- [x] case number
- [ ] safe mode (by default)

For FE, we need to style and organize the table provided.

**Comment by mamallama** [comment]
Rails will be in charge of redirecting user profile to show page upon log in

**Comment by rosalsm** [comment]
Working on PR # for part of this feature:
https://github.com/Communicant/app/pull/49
https://github.com/Communicant/app/pull/47
https://github.com/Communicant/app/pull/95
