### ISSUE TITLE
As a registered parent user I can view messages from the other parent

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#31]
Parents can see messages from the other parent in the inbox message. Each message has:
- [x] parent name
- [x] time of the message
- [x] date of the message
- [x] body of the message

For FE, It will be:
- [x] `ng-controllers` for:
  - showing messages (AJAX get)
  - sending messages (AJAX post)
  - publish new messages ($interval and $timeout)
- [x] `ng-repeat` to display all messages in the JSON
- [x] `ng-submit` to send the message
- [x] `ng-model` to send the text to the right field

**Comment by boshnivolo** [comment]
**PR for testing the angular and showing the messages generated by the backend**:
- https://github.com/Communicant/app/pull/77
- https://github.com/Communicant/app/pull/84
- https://github.com/Communicant/app/pull/86
