### ISSUE TITLE
User Story # 22. Parent can see a day in their calendar

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#35]
Same as the month view
For now it is a list of events and parents can see:
- [x] date
- [x] time
- [x] title
- [x] description????????????? too crowded right now and title is enough for the list
- [x] parent who create the event
- [x] child
- [x] mediator
- [x] pending

For FE, we organize and style the list of the events.

**Comment by mamallama** [comment]
#show page

**Comment by rosalsm** [comment]
PR working on this
https://github.com/Communicant/app/pull/45
https://github.com/Communicant/app/pull/43
https://github.com/Communicant/app/pull/42

**Comment by mamallama** [comment]
Description can just be in show page for individual event
