### ISSUE TITLE
User Story #23. Parents can see events in a week of the calendar

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#36]
The same as the view of a month in the calendar
For now it is a list of events and parents can see:
- [x] date
- [x] time
- [x] title
- [x] description????????????? too crowded right now and title is enough for the list
- [x] parent who create the event
- [x] child
- [x] mediator
- [x] pending

For FE, we organize and style the list of the events.

**Comment by rosalsm** [comment]
PR working on this
https://github.com/Communicant/app/pull/45
https://github.com/Communicant/app/pull/43
https://github.com/Communicant/app/pull/42

**Comment by mamallama** [comment]
description can be show page/for individual event
