### ISSUE TITLE
As a registered parent user I can see events related to me in the list of events

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#37]
AFTER ITERATION 2
Parents can see in the list of events view:
- [x] date
- [x] title
- [x] child
- [x] status

In addition of the list of events view, for one event view:
- [x] description 
- [x] parent who create the event
- [x] time
- [x] created by: parent/mediator

For FE, we organize and style the list of the events.

**Comment by rosalsm** [comment]
PR  release/0.0.0
https://github.com/Communicant/app/pull/45
https://github.com/Communicant/app/pull/43
https://github.com/Communicant/app/pull/42

PR release/0.1.0
https://github.com/Communicant/app/pull/82

**Comment by mamallama** [comment]
description can be show page/individual event

**Comment by rosalsm** [comment]
NOTES FROM ITERATION 2
Events.
link to each event <a>
Notes from iteration 2

Events has to show:
 who create the event (created by:), parent1, parent2, mediator.
 no sense to show the mediator.
 children name.
 pending should be a line of text saying that the event was confirmed and by who and time and date
