### ISSUE TITLE
R. As a registered user I can log in to the site 

### ISSUE THREAD

**Issue by mamallama** [Communicant/app#5]
- [x] Create Sessions controller/model
- [x] install BCrypt gem
- [x] make sure User has_secure_password
- Go through step-by-step process to ensure user authentication

User Stories: 
- User can Log in or Register(Mediator)
- User can view their own information, but no other information

**Comment by rosalsm** [comment]
The page is already done in terms of html and scss. It was done with clickable log in button and display the option of type your username and password. (can we use it in ruby??????)
- [ ] We need to create a session.
- [ ] When the mediator logs in, he goes to the mediator dash board.
- [ ] When the parents log in, they go to the calendar page.

```
User stories for Login page:

        login or register.
        view their own information but NOT the other parent information.
```

**Comment by boshnivolo** [comment]
**PR from the previous FE reop that contains my work for the Login page**:
- https://github.com/Communicant/gui/pull/5/files

**Comment by mamallama** [comment]
https://github.com/Communicant/app/pull/79
