### ISSUE TITLE
R.User Stories #25. Parents create a new event in the list of events

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#57]
User Story #25 Parents/Mediators can create a new events in list of events

Parents can add a new event in the calendar with:
- [x] date
- [x] title of event
- [x] description of event 
- [x] parent who create it
- [x] child for the event
- [x] time
- [x] pending confirmation (by default)

**Comment by mamallama** [comment]
Rails generate scaffold Events 

https://github.com/Communicant/app/commit/a29897e0e15b210b55a924c26390a50b64a345d6
