### ISSUE TITLE
R.Events List, Mediators/Parents

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#58]
User Stories: Parents/Mediators can see events list:
- [x] date
- [x] time
- [x] title
- [x] description (too crowded right now and title is enough for the list)REMOVE THIS FROM THE LIST
- [x] parent who create the event
- [x] child
- [x] mediator
- [x] pending

**Comment by mamallama** [comment]
a29897e0e15b210b55a924c26390a50b64a345d6
a2d5c6248e3579faa768d9582d6893d04f524a9b
a2d5c6248e3579faa768d9582d6893d04f524a9b
0e2a14392024a4f1ea2e082c33af1c164933f21a
