### ISSUE TITLE
R.User Stories #19. Parents can write new messages

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#60]
This will require a form in which the user inputs a message, and that form is sent to the rails app using Angular, then returned in the form of json. This JSON will include:
- [ ] parent_name
- [ ] created_at
- [ ] body  

This means adding code in the messages_controller which renders JSON for the users, and accept params :parent_name, :created_at, and :body.  If they ask for invalid credentials, the JSON should return a message telling the user that the credentials were invalid.

**Comment by ajellis** [comment]
https://github.com/Communicant/app/pull/97
