### ISSUE TITLE
R.User Stories#18. Parents can view messages to the other parents

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#61]
For Rails, this will require an API that returns the message. This JSON will include:
- [x] id
- [x] parent_name
- [x] created_at
- [x] body  

This means adding code in the messages_controller which renders JSON for the users, and accept params :parent_name, :created_at, and :body.  If they ask for invalid credentials, the JSON should return a message telling the user that the credentials were invalid.

**Comment by ajellis** [comment]
https://github.com/Communicant/app/pull/97
