### ISSUE TITLE
R. Profile: Parents can update their own profile.

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#63]
User Stories #16 Parents can update their own profile.

Create a form with: 
- [ ] Name
- [ ] Email
- [ ] Phone Number
- [ ] Address
- [ ] Child 1 Name
- [ ] Way to add More Children
- [ ] Case Number
- [ ] Mediator Name
  ---
- [ ] I need to link this through STI Users associations so that the show page loads either the Parent info or the Mediator info.
- [ ] Along with adding fields that are not already part of the profile table.

**Comment by mamallama** [comment]
I need some help with the STI stuff, but I'm getting it from alums and Rails people.
