### ISSUE TITLE
Rails: Mediators can register

### ISSUE THREAD

**Issue by ajellis** [Communicant/app#67]
In order to register they need:
- [x] first name
- [x] last name
- [x] email address
- [x] password
- [x] confirm the password
- [x] social worker/ friend/ relative ???????????????? or maybe we don't need this.

For Rails:
- [x] A form with:
  - [x] password
  - [x] email
  - [x] first_name
  - [x] last_name

This will require creating a form to add an entry to the users table. Once the form is submitted, a new entry is added to the database, with the information they provided.

**Comment by ajellis** [comment]
Renee created the database in a previous issue. The form will add a new entry to that database.

**Comment by mamallama** [comment]
All registration and profile related issues were set to iteration 4, this one and a few others were left as "Iteration 3" because parts of it were done. I'm moving it to 4.
