### ISSUE TITLE
As a registered user I can navigate to the other pages of this app using the buttons on the nav bar

### ISSUE THREAD

**Issue by rosalsm** [Communicant/app#74]
Mediators and parents can go to a different pages in the app clicking the different buttons in the header/navigation section.

Jasmine and Rosa will be working on this.

FE can do this setting ngRoute with Angular. That could be a first step in order to check if Angular works fine inside the app.

**Comment by boshnivolo** [comment]
This is no longer a front end job. We will be using `<%= link_to %>` to route the pages.
