### ISSUE TITLE
NOTES from 11/10

### ISSUE THREAD

**Issue by mamallama** [Communicant/app#81]
Events List
- [ ] #Show  
  Names:
  Change to
  Created By: Parent 
  Mediator

Neither of which should be able to be changed.
- [ ] and get rid of Pending
  Change the pending field to show when other parent 

Expenses:

Routes change to show /expenses

Styling for Update/Edit

Change Created_by instead of "Parent"
List name

Add Child Name

Don't show "Paid", Show Who Paid, When

Payment cannot be created.

Costs : Change to Expenses

Costs: When new thing added, make sure to display whether or not 

Pagination: multiple expenses costs and payments

Payments need to 

Styling: 

Columns are bunched up.
Turn Edit Destroy etc. Buttons into icons.

Turn Items listed into a link

Showing total needs to line up with total column, 
right aligned,

icons next to name of expense

indented payments

show payments total and 

expenses due date

past due in red.
### Moving Forward:
- Punchlist for User Story, Estimate
- Do AFTER enumerating: 
- User Story from Last Sprint (old)(estimate remaining):
  EXPENSES
- New User Stories (estimate)
- FE where things need to be built
- rails g empty controller 
- Merge feature branch, pull from develop, 
- pick apart design
#### Iteration
- highest priority things: 
  - bugs (easy fix)
  - bigger (in this case, Expenses)
  - figure out size of estimates. (points per S, M, L, XL)
    New stories assign to next iteration.
### On Thursday:
- Open release Branch, in description:
  - Link to deployed version
  - Link to milestone (complete and incomplete)
  - User stories included in release
  - What's in next iteration
- Environments: 
  - Development
  - Staging
  - Production = > from Master
- If functionality isn't there, remove from "done"
  
  Get around authentication: 
  Faking it.

Retrospective: 

What worked well, what didn't, what can we do better.

**Comment by mamallama** [comment]
- [ ] Confirmed by both parents option when Mediator adds event.

**Comment by al-the-x** [comment]
These are really rough notes, which is fine for starts, but probably best left in a notebook until the team comes to a shared understanding and adds in all the necessary details from _their_ notes, too. FWIW, a Punchlist should be _a single checklist_ that can be tackled _quickly and efficiently_ in _a single branch_ (preferably the release branch, but oh well), possibly by a single person or pair.
